# Start with the same Node.js base image
FROM node:20-bookworm-slim

WORKDIR /usr/src/app

# Update package lists and install a minimal, but functional, TeX Live distribution.
# This selection is much smaller than 'texlive-full' but should cover most
# resume compilation needs.
RUN
# tbd

# Copy your application's dependency manifests
COPY package*.json ./

# Install your Node.js application dependencies
RUN npm install

# Copy the rest of your application source code into the container
COPY . .

# Expose the port your Express app will be listening on
EXPOSE 3000

# Define the command that will be run when the container starts
CMD [ "node", "server.js" ]
